---
version: "2"

services:

  idp1:
    build:
      context: ./idp1
    image: inacademia-idp1:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local idp:172.21.10.201
    hostname: idp1
    volumes:
      - "./idp1/config/metadata:/var/www/simplesamlphp/metadata"
    expose:
      - 80
      - 443
    networks:
      inacademia:
        ipv4_address: 172.21.10.201

  idp2:
    build:
      context: ./idp2
    image: inacademia-idp2:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp2.inacademia.local idp:172.21.10.202
    hostname: idp2
    volumes:
      - "./idp2/config/metadata:/var/www/simplesamlphp/metadata"
    expose:
      - 80
      - 443
    networks:
      inacademia:
        ipv4_address: 172.21.10.202

  idp3:
    build:
      context: ./shib-idp
    image: inacademia-shib-idp:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp3.inacademia.local idp:172.21.10.203
    hostname: idp
    volumes:
      - "./shib-idp/app:/tmp/app"
      - "./shib-idp/config:/tmp/config"
    expose:
      - 80
      - 443
      - 389
    networks:
      inacademia:
        ipv4_address: 172.21.10.203

  op:
    build:
      context: ./op
    image: inacademia-op:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local:172.21.10.201
      - idp2.inacademia.local:172.21.10.202
      - idp3.inacademia.local:172.21.10.203
    hostname: op
    volumes:
      - ./${POUND_SSL_DIR}:/etc/ssl
    environment:
      BACKEND_PORT: tcp://172.21.10.2:80
      REWRITE_LOCATION: 1
    expose:
      - 80
      - 443
    networks:
      inacademia:
        ipv4_address: 172.21.10.3

  rp:
    build:
      context: ./rp
    image: inacademia-rp:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local:172.21.10.201
      - idp2.inacademia.local:172.21.10.202
      - idp3.inacademia.local:172.21.10.203
    hostname: rp
    expose:
      - 80
      - 443
    networks:
      inacademia:
        ipv4_address: 172.21.10.100

  mdq:
    build:
      context: ./mdq
      args:
        - PYFF_VERSION=${PYFF_VERSION}
    image: inacademia-mdq:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local:172.21.10.201
      - idp2.inacademia.local:172.21.10.202
      - idp3.inacademia.local:172.21.10.203
    hostname: mdq
    volumes:
      - ./mdq/config/mdq.fd:/opt/mdq.fd
      - ./mdq/config/metadata:/opt/metadata
    expose:
      - 80
      - 443
    depends_on:
      - "idp1"
      - "idp2"
      - "idp3"
    networks:
      inacademia:
        ipv4_address: 172.21.10.4

  svs-dev:
    build:
      context: ./svs-dev
    image: inacademia-svs-dev:v1
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local:172.21.10.201
      - idp2.inacademia.local:172.21.10.202
      - idp3.inacademia.local:172.21.10.203
    hostname: svs
    volumes:
      - ./svs-dev/config/production:/var/svs
      - ./svs-dev/config/cdb:/etc/cdb
      - ./svs-dev/workdir:/opt/workdir
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${GIT_KEY}:/tmp/inacademia/id_rsa_inacademia
    environment:
      SATOSA_TAG: ${SATOSA_VERSION}
      SVS_TAG: ${SVS_VERSION}
      PROXY_PORT: 80
      DATA_DIR: /var/svs
      SATOSA_STATE_ENCRYPTION_KEY: ${SATOSA_KEY}
      SATOSA_USER_ID_HASH_SALT: ${SATOSA_SALT}
    working_dir: /var/svs
    depends_on:
      - "op"
      - "rp"
      - "mdq"
    expose:
      - 80
    networks:
      inacademia:
        ipv4_address: 172.21.10.2

  svs:
    build:
      context: ./svs
      dockerfile: Dockerfile
      args:
        - SATOSA_VERSION=${SATOSA_VERSION}
        - SVS_VERSION=${SVS_VERSION}
    image: ${IMAGE_NAME}:v${IMAGE_VERSION}_${DOCKER_VERSION}
    extra_hosts:
      - svs.inacademia.local:172.21.10.2
      - op.inacademia.local:172.21.10.3
      - mdq.inacademia.local:172.21.10.4
      - rp.inacademia.local:172.21.10.100
      - idp1.inacademia.local:172.21.10.201
      - idp2.inacademia.local:172.21.10.202
      - idp3.inacademia.local:172.21.10.203
    hostname: svs
    volumes:
      - ./svs/config/production:/var/svs
      - ./svs/config/cdb:/etc/cdb
      - ./svs/workdir:/opt/workdir
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      PROXY_PORT: 80
      DATA_DIR: /var/svs
      SATOSA_STATE_ENCRYPTION_KEY: ${SATOSA_KEY}
      SATOSA_USER_ID_HASH_SALT: ${SATOSA_SALT}
    working_dir: /var/svs
    depends_on:
      - "op"
      - "rp"
      - "mdq"
    expose:
      - 80
    networks:
      inacademia:
        ipv4_address: 172.21.10.2

networks:
  inacademia:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.10.0/24
          gateway: 172.21.10.1
